applications:
- name: init-app
  namespace: argo
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  project: default
  source:
    repoURL: 'https://github.com/DzeCin/argo'
    path: .
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground